In [113]:
import csv

# Data Analysis Process

### Step 1: Get data

Categorical Data - Any value that if you ran mathematical operation on, you'd get nonsensical data

Ordinal Data - Any value that if you ran mathematical operation on it, you'd get sensical data

### Step 2: Clean Data

In [114]:
enrollment_data = []
file = open('./enrollments.csv', 'r' )
data = csv.DictReader(file)
for i in data:
    enrollment_data.append(i)
file.close()

In [115]:
len(enrollment_data)

1640

In [116]:
enrollment_data[0]

{'account_key': '700',
 'status': 'canceled',
 'join_date': '2017-11-10',
 'cancel_date': '2017-11-16',
 'days_to_cancel': '6',
 'is_enrolled': 'FALSE',
 'is_canceled': 'TRUE'}

In [117]:
def read_from_csv(filepath):
    with open(filepath) as file:
        data = csv.DictReader(file)
        return list(data)

enrollment_data = read_from_csv('./enrollments.csv')
engagement_data = read_from_csv('./engagements.csv')
submission_data = read_from_csv('./submissions.csv')

In [118]:
enrollment_data[0]

{'account_key': '700',
 'status': 'canceled',
 'join_date': '2017-11-10',
 'cancel_date': '2017-11-16',
 'days_to_cancel': '6',
 'is_enrolled': 'FALSE',
 'is_canceled': 'TRUE'}

In [119]:
engagement_data[0]

{'acct': '0',
 'utc_date': '2018-01-09',
 'num_courses_visited': '1',
 'total_minutes_visited': '11.6793745',
 'lessons_completed': '0',
 'projects_completed': '0'}

In [120]:
submission_data[0]

{'creation_date': '2018-01-14',
 'completion_date': '2018-01-16',
 'assigned_rating': 'UNGRADED',
 'account_key': '256',
 'lesson_key': '3176718735',
 'processing_state': 'EVALUATED'}

In [121]:
from datetime import datetime as dt

In [122]:
dt.strptime('2018-01-14', '%Y-%m-%d')

datetime.datetime(2018, 1, 14, 0, 0)

In [123]:
dt.strftime(dt(2018, 1, 14, 0, 0), '%Y-%m-%d')

'2018-01-14'

In [124]:
dt.now()

datetime.datetime(2022, 3, 9, 17, 38, 57, 891661)

In [125]:
dt.strftime(dt.now(), '%Y-%m-%d %M:%S')

'2022-03-09 38:57'

In [126]:
def convert_to_date(string):
    if string == '':
        return None
    return dt.strptime(string, '%Y-%m-%d')

def convert_to_bool(string):
    if string == '':
        return None
    elif string == 'TRUE':
        return True
    elif string == 'FALSE':
        return False

def convert_to_int(string):
    if string == '':
        return None
    return int(string)

def convert_to_float(string):
    if string == '':
        return None
    return float(string)

In [127]:
for r in enrollment_data:
    r['join_date'] = convert_to_date(r['join_date'])
    r['cancel_date'] = convert_to_date(r['cancel_date'])
    r['days_to_cancel'] = convert_to_int(r['days_to_cancel'])
    r['is_enrolled'] = convert_to_bool(r['is_enrolled'])
    r['is_canceled'] = convert_to_bool(r['is_canceled'])

In [128]:
for r in engagement_data:
    r['utc_date'] = convert_to_date(r['utc_date'])
    r['num_courses_visited'] = convert_to_int(r['num_courses_visited'])
    r['total_minutes_visited'] = convert_to_float(r['total_minutes_visited'])
    r['lessons_completed'] = convert_to_int(r['lessons_completed'])
    r['projects_completed'] = convert_to_int(r['projects_completed'])

In [129]:
for r in submission_data:
    r['creation_date'] = convert_to_date(r['creation_date'])
    r['completion_date'] = convert_to_date(r['completion_date'])
    # r['assigned_rating'] = convert_to_float(r['assigned_rating'])
    # r['account_key'] = convert_to_int(r['account_key'])
    # r['lesson_key'] = convert_to_int(r['lesson_key'])
    # r['processing_state'] = convert_to_bool(r['projects_completed'])

In [130]:
for r in engagement_data:
    r['account_key'] = r['acct']
    del r['acct']

In [131]:
engagement_data[0]

{'utc_date': datetime.datetime(2018, 1, 9, 0, 0),
 'num_courses_visited': 1,
 'total_minutes_visited': 11.6793745,
 'lessons_completed': 0,
 'projects_completed': 0,
 'account_key': '0'}

In [132]:
def get_unique_records(dataset, column_name):
    unique_data = set()
    for row in dataset:
        unique_data.add(row[column_name])
    return unique_data

In [133]:
unique_enrollments = get_unique_records(enrollment_data, 'account_key')
unique_engagements = get_unique_records(engagement_data, 'account_key')
unique_submissions = get_unique_records(submission_data, 'account_key')

In [134]:
print(len(unique_enrollments))
print(len(unique_engagements))
print(len(unique_submissions))

1302
1237
743

In [135]:
outliers = 0
for r in enrollment_data:
    if r['account_key'] not in unique_engagements and r['join_date'] != r['cancel_date']:
        outliers += 1
        print(r, end='\n\n')

{'account_key': '1304', 'status': 'canceled', 'join_date': datetime.datetime(2018, 1, 10, 0, 0), 'cancel_date': datetime.datetime(2018, 3, 10, 0, 0), 'days_to_cancel': 59, 'is_enrolled': True, 'is_canceled': True}

{'account_key': '1304', 'status': 'canceled', 'join_date': datetime.datetime(2018, 3, 10, 0, 0), 'cancel_date': datetime.datetime(2018, 6, 17, 0, 0), 'days_to_cancel': 99, 'is_enrolled': True, 'is_canceled': True}

{'account_key': '1101', 'status': 'current', 'join_date': datetime.datetime(2018, 2, 25, 0, 0), 'cancel_date': None, 'days_to_cancel': None, 'is_enrolled': True, 'is_canceled': False}

In [136]:
test_accounts = set()
for r in enrollment_data:
    if r['is_enrolled']:
        test_accounts.add(r['account_key'])

print(len(test_accounts))

6

In [137]:
test_accounts

{'1069', '1101', '1304', '312', '448', '818'}

In [138]:
def remove_test_accounts(dataset):
    records_to_remove = []
    for row_dict in dataset:
        if row_dict['account_key'] not in test_accounts:
            records_to_remove.append(row_dict)
    return records_to_remove

In [139]:
true_enrollments = remove_test_accounts(enrollment_data)
true_engagements = remove_test_accounts(engagement_data)
true_submissions = remove_test_accounts(submission_data)

In [140]:
print(len(true_enrollments))
print(len(true_engagements))
print(len(true_submissions))

1622
135656
3634

### Step 3: Answer Questions with Data

<h4>Find quality accounts in which:</h4>
<ol>
    <li>The account is currently active i.e. is_canceled is False</li>
    <li>days_to_cancel is greater than 7 i.e. the trial period</li>
    <li>The latest vald record for each particular VALID user</li>
</ol>

In [141]:
accounts_in_good_standing = dict()
for row_dict in true_enrollments:
    if row_dict['days_to_cancel'] is not None and row_dict['cancel_date'] is not None:
        if not row_dict['is_canceled'] or row_dict['days_to_cancel'] > 7:
            if row_dict['account_key'] not in accounts_in_good_standing or row_dict['join_date'] > accounts_in_good_standing[row_dict['account_key']]:
                accounts_in_good_standing[row_dict['account_key']] = row_dict['join_date']

In [142]:
accounts_in_good_standing

{'429': datetime.datetime(2018, 3, 10, 0, 0),
 '60': datetime.datetime(2018, 1, 14, 0, 0),
 '322': datetime.datetime(2018, 2, 12, 0, 0),
 '584': datetime.datetime(2018, 1, 14, 0, 0),
 '458': datetime.datetime(2017, 11, 10, 0, 0),
 '1058': datetime.datetime(2018, 1, 14, 0, 0),
 '45': datetime.datetime(2017, 11, 10, 0, 0),
 '315': datetime.datetime(2017, 11, 10, 0, 0),
 '408': datetime.datetime(2018, 4, 1, 0, 0),
 '51': datetime.datetime(2018, 3, 10, 0, 0),
 '323': datetime.datetime(2017, 11, 10, 0, 0),
 '130': datetime.datetime(2018, 4, 1, 0, 0),
 '550': datetime.datetime(2018, 5, 28, 0, 0),
 '44': datetime.datetime(2017, 11, 10, 0, 0),
 '440': datetime.datetime(2017, 11, 11, 0, 0),
 '57': datetime.datetime(2017, 11, 11, 0, 0),
 '1090': datetime.datetime(2017, 11, 11, 0, 0),
 '541': datetime.datetime(2017, 11, 12, 0, 0),
 '756': datetime.datetime(2017, 11, 15, 0, 0),
 '101': datetime.datetime(2017, 11, 12, 0, 0),
 '800': datetime.datetime(2018, 3, 4, 0, 0),
 '702': datetime.datetime(2018, 1, 14, 0, 0),
 '744': datetime.datetime(2017, 11, 14, 0, 0),
 '217': datetime.datetime(2017, 11, 15, 0, 0),
 '1211': datetime.datetime(2017, 11, 15, 0, 0),
 '53': datetime.datetime(2017, 11, 14, 0, 0),
 '338': datetime.datetime(2018, 2, 3, 0, 0),
 '253': datetime.datetime(2017, 11, 16, 0, 0),
 '178': datetime.datetime(2017, 11, 17, 0, 0),
 '822': datetime.datetime(2017, 11, 17, 0, 0),
 '123': datetime.datetime(2018, 3, 10, 0, 0),
 '1204': datetime.datetime(2017, 11, 10, 0, 0),
 '394': datetime.datetime(2017, 11, 10, 0, 0),
 '1253': datetime.datetime(2017, 11, 10, 0, 0),
 '504': datetime.datetime(2017, 11, 10, 0, 0),
 '72': datetime.datetime(2017, 11, 10, 0, 0),
 '268': datetime.datetime(2018, 4, 3, 0, 0),
 '339': datetime.datetime(2018, 4, 1, 0, 0),
 '1244': datetime.datetime(2018, 5, 17, 0, 0),
 '752': datetime.datetime(2017, 11, 10, 0, 0),
 '520': datetime.datetime(2017, 11, 10, 0, 0),
 '367': datetime.datetime(2017, 11, 11, 0, 0),
 '258': datetime.datetime(2017, 11, 10, 0, 0),
 '329': datetime.datetime(2018, 3, 10, 0, 0),
 '612': datetime.datetime(2017, 11, 10, 0, 0),
 '150': datetime.datetime(2017, 11, 10, 0, 0),
 '179': datetime.datetime(2017, 11, 10, 0, 0),
 '587': datetime.datetime(2018, 1, 14, 0, 0),
 '439': datetime.datetime(2017, 11, 10, 0, 0),
 '18': datetime.datetime(2017, 11, 10, 0, 0),
 '544': datetime.datetime(2017, 11, 10, 0, 0),
 '913': datetime.datetime(2018, 1, 14, 0, 0),
 '576': datetime.datetime(2017, 11, 10, 0, 0),
 '431': datetime.datetime(2017, 11, 10, 0, 0),
 '480': datetime.datetime(2018, 3, 10, 0, 0),
 '525': datetime.datetime(2017, 11, 10, 0, 0),
 '1111': datetime.datetime(2018, 4, 1, 0, 0),
 '1107': datetime.datetime(2017, 11, 11, 0, 0),
 '577': datetime.datetime(2018, 2, 5, 0, 0),
 '92': datetime.datetime(2017, 11, 12, 0, 0),
 '335': datetime.datetime(2017, 11, 12, 0, 0),
 '693': datetime.datetime(2018, 1, 14, 0, 0),
 '88': datetime.datetime(2018, 3, 10, 0, 0),
 '983': datetime.datetime(2018, 1, 14, 0, 0),
 '1118': datetime.datetime(2017, 11, 17, 0, 0),
 '499': datetime.datetime(2018, 2, 6, 0, 0),
 '590': datetime.datetime(2018, 2, 3, 0, 0),
 '264': datetime.datetime(2018, 2, 3, 0, 0),
 '1130': datetime.datetime(2017, 12, 3, 0, 0),
 '736': datetime.datetime(2017, 12, 4, 0, 0),
 '976': datetime.datetime(2017, 12, 4, 0, 0),
 '316': datetime.datetime(2017, 12, 6, 0, 0),
 '347': datetime.datetime(2017, 12, 7, 0, 0),
 '343': datetime.datetime(2017, 12, 7, 0, 0),
 '221': datetime.datetime(2017, 12, 3, 0, 0),
 '631': datetime.datetime(2018, 5, 8, 0, 0),
 '1009': datetime.datetime(2017, 12, 5, 0, 0),
 '909': datetime.datetime(2017, 12, 5, 0, 0),
 '524': datetime.datetime(2017, 12, 6, 0, 0),
 '759': datetime.datetime(2018, 2, 3, 0, 0),
 '896': datetime.datetime(2018, 3, 10, 0, 0),
 '411': datetime.datetime(2018, 4, 8, 0, 0),
 '705': datetime.datetime(2018, 4, 8, 0, 0),
 '776': datetime.datetime(2017, 12, 8, 0, 0),
 '557': datetime.datetime(2018, 2, 3, 0, 0),
 '634': datetime.datetime(2017, 12, 9, 0, 0),
 '1124': datetime.datetime(2018, 2, 3, 0, 0),
 '932': datetime.datetime(2017, 12, 9, 0, 0),
 '169': datetime.datetime(2018, 2, 5, 0, 0),
 '229': datetime.datetime(2018, 1, 7, 0, 0),
 '622': datetime.datetime(2018, 1, 8, 0, 0),
 '730': datetime.datetime(2018, 1, 8, 0, 0),
 '905': datetime.datetime(2018, 1, 8, 0, 0),
 '170': datetime.datetime(2018, 1, 9, 0, 0),
 '467': datetime.datetime(2018, 1, 10, 0, 0),
 '780': datetime.datetime(2018, 1, 11, 0, 0),
 '418': datetime.datetime(2018, 1, 11, 0, 0),
 '1074': datetime.datetime(2018, 3, 10, 0, 0),
 '859': datetime.datetime(2018, 1, 11, 0, 0),
 '91': datetime.datetime(2017, 11, 10, 0, 0),
 '3': datetime.datetime(2017, 11, 10, 0, 0),
 '157': datetime.datetime(2018, 3, 10, 0, 0),
 '378': datetime.datetime(2018, 3, 10, 0, 0),
 '1214': datetime.datetime(2017, 11, 10, 0, 0),
 '483': datetime.datetime(2017, 11, 10, 0, 0),
 '1094': datetime.datetime(2017, 11, 10, 0, 0),
 '882': datetime.datetime(2017, 11, 10, 0, 0),
 '412': datetime.datetime(2018, 3, 10, 0, 0),
 '366': datetime.datetime(2018, 4, 1, 0, 0),
 '696': datetime.datetime(2017, 11, 10, 0, 0),
 '1142': datetime.datetime(2018, 3, 10, 0, 0),
 '148': datetime.datetime(2018, 4, 1, 0, 0),
 '630': datetime.datetime(2017, 11, 11, 0, 0),
 '1011': datetime.datetime(2018, 4, 8, 0, 0),
 '161': datetime.datetime(2017, 11, 12, 0, 0),
 '441': datetime.datetime(2017, 11, 12, 0, 0),
 '712': datetime.datetime(2017, 11, 13, 0, 0),
 '76': datetime.datetime(2017, 11, 15, 0, 0),
 '938': datetime.datetime(2017, 11, 14, 0, 0),
 '829': datetime.datetime(2017, 11, 15, 0, 0),
 '203': datetime.datetime(2018, 5, 12, 0, 0),
 '563': datetime.datetime(2017, 12, 3, 0, 0),
 '1167': datetime.datetime(2017, 12, 3, 0, 0),
 '643': datetime.datetime(2018, 4, 8, 0, 0),
 '110': datetime.datetime(2017, 12, 3, 0, 0),
 '1289': datetime.datetime(2017, 12, 4, 0, 0),
 '500': datetime.datetime(2017, 12, 5, 0, 0),
 '1160': datetime.datetime(2017, 12, 5, 0, 0),
 '64': datetime.datetime(2017, 12, 6, 0, 0),
 '637': datetime.datetime(2018, 5, 6, 0, 0),
 '52': datetime.datetime(2017, 12, 7, 0, 0),
 '111': datetime.datetime(2017, 12, 7, 0, 0),
 '583': datetime.datetime(2017, 12, 8, 0, 0),
 '1199': datetime.datetime(2017, 12, 8, 0, 0),
 '743': datetime.datetime(2017, 12, 9, 0, 0),
 '474': datetime.datetime(2017, 12, 9, 0, 0),
 '667': datetime.datetime(2017, 12, 9, 0, 0),
 '1095': datetime.datetime(2018, 6, 6, 0, 0),
 '79': datetime.datetime(2017, 12, 9, 0, 0),
 '197': datetime.datetime(2018, 1, 7, 0, 0),
 '67': datetime.datetime(2018, 1, 7, 0, 0),
 '678': datetime.datetime(2018, 1, 8, 0, 0),
 '873': datetime.datetime(2018, 1, 8, 0, 0),
 '623': datetime.datetime(2018, 1, 8, 0, 0),
 '507': datetime.datetime(2018, 1, 9, 0, 0),
 '270': datetime.datetime(2018, 1, 9, 0, 0),
 '362': datetime.datetime(2018, 2, 5, 0, 0),
 '263': datetime.datetime(2018, 6, 1, 0, 0),
 '965': datetime.datetime(2018, 1, 10, 0, 0),
 '761': datetime.datetime(2018, 1, 11, 0, 0),
 '785': datetime.datetime(2018, 4, 8, 0, 0),
 '989': datetime.datetime(2018, 4, 8, 0, 0),
 '682': datetime.datetime(2018, 4, 8, 0, 0),
 '671': datetime.datetime(2017, 12, 9, 0, 0),
 '1121': datetime.datetime(2018, 1, 12, 0, 0),
 '966': datetime.datetime(2018, 1, 7, 0, 0),
 '442': datetime.datetime(2018, 3, 15, 0, 0),
 '5': datetime.datetime(2018, 1, 7, 0, 0),
 '34': datetime.datetime(2018, 1, 8, 0, 0),
 '824': datetime.datetime(2018, 2, 10, 0, 0),
 '1060': datetime.datetime(2018, 1, 11, 0, 0),
 '227': datetime.datetime(2017, 11, 12, 0, 0),
 '599': datetime.datetime(2018, 1, 14, 0, 0),
 '181': datetime.datetime(2017, 11, 13, 0, 0),
 '639': datetime.datetime(2017, 11, 13, 0, 0),
 '1303': datetime.datetime(2018, 4, 8, 0, 0),
 '969': datetime.datetime(2017, 11, 14, 0, 0),
 '972': datetime.datetime(2018, 3, 10, 0, 0),
 '334': datetime.datetime(2017, 11, 16, 0, 0),
 '1277': datetime.datetime(2018, 1, 14, 0, 0),
 '1071': datetime.datetime(2018, 1, 14, 0, 0),
 '923': datetime.datetime(2018, 1, 14, 0, 0),
 '640': datetime.datetime(2018, 3, 10, 0, 0),
 '1174': datetime.datetime(2018, 2, 3, 0, 0),
 '1019': datetime.datetime(2017, 11, 11, 0, 0),
 '655': datetime.datetime(2017, 11, 10, 0, 0),
 '529': datetime.datetime(2017, 12, 8, 0, 0),
 '256': datetime.datetime(2018, 4, 1, 0, 0),
 '523': datetime.datetime(2018, 1, 12, 0, 0),
 '24': datetime.datetime(2017, 12, 3, 0, 0),
 '397': datetime.datetime(2017, 12, 4, 0, 0),
 '265': datetime.datetime(2017, 12, 4, 0, 0),
 '650': datetime.datetime(2018, 3, 4, 0, 0),
 '1013': datetime.datetime(2018, 4, 1, 0, 0),
 '618': datetime.datetime(2017, 12, 5, 0, 0),
 '1236': datetime.datetime(2017, 12, 5, 0, 0),
 '866': datetime.datetime(2017, 12, 7, 0, 0),
 '1201': datetime.datetime(2017, 12, 7, 0, 0),
 '193': datetime.datetime(2017, 12, 8, 0, 0),
 '710': datetime.datetime(2018, 2, 3, 0, 0),
 '180': datetime.datetime(2018, 3, 10, 0, 0),
 '722': datetime.datetime(2018, 3, 10, 0, 0),
 '954': datetime.datetime(2018, 3, 10, 0, 0),
 '140': datetime.datetime(2017, 11, 10, 0, 0),
 '1139': datetime.datetime(2018, 1, 16, 0, 0),
 '388': datetime.datetime(2017, 12, 8, 0, 0),
 '147': datetime.datetime(2017, 12, 3, 0, 0),
 '119': datetime.datetime(2018, 2, 3, 0, 0),
 '97': datetime.datetime(2018, 2, 5, 0, 0),
 '984': datetime.datetime(2018, 2, 5, 0, 0),
 '444': datetime.datetime(2018, 2, 5, 0, 0),
 '386': datetime.datetime(2018, 4, 8, 0, 0),
 '649': datetime.datetime(2017, 11, 10, 0, 0),
 '165': datetime.datetime(2017, 11, 10, 0, 0),
 '580': datetime.datetime(2017, 11, 10, 0, 0),
 '919': datetime.datetime(2017, 11, 10, 0, 0),
 '90': datetime.datetime(2018, 3, 10, 0, 0),
 '864': datetime.datetime(2017, 11, 10, 0, 0),
 '626': datetime.datetime(2018, 3, 4, 0, 0),
 '1117': datetime.datetime(2017, 11, 11, 0, 0),
 '187': datetime.datetime(2017, 11, 12, 0, 0),
 '547': datetime.datetime(2018, 2, 3, 0, 0),
 '159': datetime.datetime(2017, 12, 9, 0, 0),
 '1226': datetime.datetime(2018, 4, 8, 0, 0),
 '857': datetime.datetime(2018, 2, 6, 0, 0),
 '143': datetime.datetime(2018, 2, 9, 0, 0),
 '138': datetime.datetime(2018, 2, 10, 0, 0),
 '952': datetime.datetime(2018, 2, 11, 0, 0),
 '416': datetime.datetime(2018, 4, 8, 0, 0),
 '477': datetime.datetime(2018, 3, 4, 0, 0),
 '132': datetime.datetime(2018, 3, 4, 0, 0),
 '624': datetime.datetime(2018, 3, 4, 0, 0),
 '1247': datetime.datetime(2018, 3, 5, 0, 0),
 '251': datetime.datetime(2018, 2, 6, 0, 0),
 '709': datetime.datetime(2018, 2, 8, 0, 0),
 '564': datetime.datetime(2018, 2, 8, 0, 0),
 '792': datetime.datetime(2018, 2, 9, 0, 0),
 '833': datetime.datetime(2018, 2, 9, 0, 0),
 '823': datetime.datetime(2018, 4, 8, 0, 0),
 '348': datetime.datetime(2018, 2, 5, 0, 0),
 '185': datetime.datetime(2018, 3, 10, 0, 0),
 '855': datetime.datetime(2017, 11, 14, 0, 0),
 '191': datetime.datetime(2017, 11, 16, 0, 0),
 '261': datetime.datetime(2017, 11, 16, 0, 0),
 '415': datetime.datetime(2017, 11, 16, 0, 0),
 '868': datetime.datetime(2017, 11, 16, 0, 0),
 '719': datetime.datetime(2017, 11, 17, 0, 0),
 '836': datetime.datetime(2017, 12, 9, 0, 0),
 '108': datetime.datetime(2018, 4, 20, 0, 0),
 '285': datetime.datetime(2018, 1, 7, 0, 0),
 '698': datetime.datetime(2018, 1, 8, 0, 0),
 '427': datetime.datetime(2018, 1, 9, 0, 0),
 '1212': datetime.datetime(2018, 7, 19, 0, 0),
 '1140': datetime.datetime(2018, 1, 10, 0, 0),
 '505': datetime.datetime(2018, 3, 7, 0, 0),
 '171': datetime.datetime(2018, 3, 8, 0, 0),
 '1102': datetime.datetime(2018, 4, 8, 0, 0),
 '1287': datetime.datetime(2018, 3, 10, 0, 0),
 '1254': datetime.datetime(2018, 1, 10, 0, 0),
 '1259': datetime.datetime(2018, 1, 13, 0, 0),
 '1128': datetime.datetime(2018, 3, 11, 0, 0),
 '78': datetime.datetime(2017, 12, 8, 0, 0),
 '558': datetime.datetime(2017, 12, 3, 0, 0),
 '153': datetime.datetime(2018, 4, 1, 0, 0),
 '473': datetime.datetime(2018, 4, 1, 0, 0),
 '106': datetime.datetime(2017, 11, 11, 0, 0),
 '74': datetime.datetime(2018, 4, 1, 0, 0),
 '591': datetime.datetime(2018, 3, 10, 0, 0),
 '419': datetime.datetime(2018, 3, 10, 0, 0),
 '31': datetime.datetime(2017, 11, 10, 0, 0),
 '69': datetime.datetime(2018, 3, 10, 0, 0),
 '906': datetime.datetime(2017, 11, 17, 0, 0),
 '601': datetime.datetime(2017, 11, 10, 0, 0),
 '321': datetime.datetime(2018, 3, 10, 0, 0),
 '99': datetime.datetime(2018, 3, 10, 0, 0),
 '1103': datetime.datetime(2018, 3, 10, 0, 0),
 '1066': datetime.datetime(2018, 3, 10, 0, 0),
 '571': datetime.datetime(2017, 12, 8, 0, 0),
 '426': datetime.datetime(2018, 5, 7, 0, 0),
 '98': datetime.datetime(2018, 4, 2, 0, 0),
 '757': datetime.datetime(2018, 1, 11, 0, 0),
 '151': datetime.datetime(2018, 1, 11, 0, 0),
 '534': datetime.datetime(2018, 1, 12, 0, 0),
 '597': datetime.datetime(2018, 1, 12, 0, 0),
 '1242': datetime.datetime(2018, 1, 12, 0, 0),
 '732': datetime.datetime(2018, 1, 12, 0, 0),
 '168': datetime.datetime(2018, 2, 5, 0, 0),
 '657': datetime.datetime(2018, 3, 10, 0, 0),
 '831': datetime.datetime(2017, 12, 3, 0, 0),
 '1015': datetime.datetime(2017, 12, 3, 0, 0),
 '611': datetime.datetime(2017, 12, 8, 0, 0),
 '62': datetime.datetime(2017, 12, 8, 0, 0),
 '697': datetime.datetime(2017, 12, 8, 0, 0),
 '43': datetime.datetime(2017, 12, 8, 0, 0),
 '769': datetime.datetime(2018, 4, 3, 0, 0),
 '1123': datetime.datetime(2018, 4, 3, 0, 0),
 '918': datetime.datetime(2018, 4, 6, 0, 0),
 '1248': datetime.datetime(2018, 4, 6, 0, 0),
 '1189': datetime.datetime(2018, 4, 7, 0, 0),
 '1285': datetime.datetime(2018, 4, 7, 0, 0),
 '844': datetime.datetime(2018, 4, 7, 0, 0),
 '690': datetime.datetime(2018, 2, 5, 0, 0),
 '641': datetime.datetime(2018, 4, 7, 0, 0),
 '404': datetime.datetime(2018, 4, 8, 0, 0),
 '105': datetime.datetime(2018, 4, 7, 0, 0),
 '1299': datetime.datetime(2018, 2, 5, 0, 0),
 '589': datetime.datetime(2018, 2, 5, 0, 0),
 '793': datetime.datetime(2018, 4, 8, 0, 0),
 '243': datetime.datetime(2017, 11, 16, 0, 0),
 '1163': datetime.datetime(2018, 5, 6, 0, 0),
 '948': datetime.datetime(2018, 5, 6, 0, 0),
 '1202': datetime.datetime(2018, 5, 7, 0, 0),
 '867': datetime.datetime(2017, 12, 9, 0, 0),
 '1292': datetime.datetime(2018, 1, 7, 0, 0),
 '93': datetime.datetime(2018, 1, 7, 0, 0),
 '460': datetime.datetime(2018, 1, 7, 0, 0),
 '610': datetime.datetime(2018, 1, 7, 0, 0),
 '670': datetime.datetime(2018, 1, 8, 0, 0),
 '900': datetime.datetime(2018, 1, 10, 0, 0),
 '1053': datetime.datetime(2018, 1, 11, 0, 0),
 '934': datetime.datetime(2018, 1, 11, 0, 0),
 '746': datetime.datetime(2018, 2, 5, 0, 0),
 '279': datetime.datetime(2018, 2, 5, 0, 0),
 '136': datetime.datetime(2018, 2, 5, 0, 0),
 '1042': datetime.datetime(2018, 5, 28, 0, 0),
 '413': datetime.datetime(2018, 2, 6, 0, 0),
 '306': datetime.datetime(2018, 2, 8, 0, 0),
 '284': datetime.datetime(2018, 2, 9, 0, 0),
 '521': datetime.datetime(2018, 4, 8, 0, 0),
 '1049': datetime.datetime(2018, 2, 10, 0, 0),
 '1198': datetime.datetime(2018, 3, 4, 0, 0),
 '720': datetime.datetime(2018, 3, 4, 0, 0),
 '958': datetime.datetime(2018, 3, 4, 0, 0),
 '718': datetime.datetime(2018, 5, 8, 0, 0),
 '293': datetime.datetime(2018, 5, 10, 0, 0),
 '858': datetime.datetime(2018, 5, 12, 0, 0),
 '713': datetime.datetime(2018, 5, 12, 0, 0),
 '1040': datetime.datetime(2018, 5, 12, 0, 0),
 '1305': datetime.datetime(2018, 5, 12, 0, 0),
 '25': datetime.datetime(2017, 11, 11, 0, 0),
 '988': datetime.datetime(2018, 5, 13, 0, 0),
 '877': datetime.datetime(2018, 5, 13, 0, 0),
 '42': datetime.datetime(2018, 3, 4, 0, 0),
 '704': datetime.datetime(2018, 5, 6, 0, 0),
 '407': datetime.datetime(2018, 5, 6, 0, 0),
 '1029': datetime.datetime(2018, 5, 12, 0, 0),
 '465': datetime.datetime(2018, 2, 5, 0, 0),
 '208': datetime.datetime(2018, 3, 8, 0, 0),
 '1260': datetime.datetime(2018, 3, 11, 0, 0),
 '1194': datetime.datetime(2018, 3, 11, 0, 0),
 '361': datetime.datetime(2018, 5, 13, 0, 0),
 '220': datetime.datetime(2018, 4, 7, 0, 0),
 '1266': datetime.datetime(2018, 6, 7, 0, 0),
 '735': datetime.datetime(2018, 4, 14, 0, 0),
 '1183': datetime.datetime(2018, 7, 17, 0, 0),
 '804': datetime.datetime(2018, 6, 9, 0, 0),
 '1208': datetime.datetime(2018, 2, 5, 0, 0),
 '1207': datetime.datetime(2018, 2, 6, 0, 0),
 '602': datetime.datetime(2018, 2, 6, 0, 0),
 '1153': datetime.datetime(2018, 2, 6, 0, 0),
 '1210': datetime.datetime(2018, 2, 7, 0, 0),
 '916': datetime.datetime(2018, 2, 8, 0, 0),
 '666': datetime.datetime(2018, 2, 9, 0, 0),
 '753': datetime.datetime(2018, 3, 5, 0, 0),
 '141': datetime.datetime(2018, 3, 7, 0, 0),
 '729': datetime.datetime(2018, 4, 3, 0, 0),
 '1089': datetime.datetime(2018, 4, 6, 0, 0),
 '651': datetime.datetime(2018, 4, 6, 0, 0),
 '1054': datetime.datetime(2018, 4, 7, 0, 0),
 '289': datetime.datetime(2018, 4, 7, 0, 0),
 '796': datetime.datetime(2018, 4, 7, 0, 0),
 '1205': datetime.datetime(2018, 7, 17, 0, 0),
 '856': datetime.datetime(2018, 7, 18, 0, 0),
 '786': datetime.datetime(2018, 4, 2, 0, 0),
 '1264': datetime.datetime(2018, 4, 2, 0, 0),
 '1088': datetime.datetime(2018, 4, 3, 0, 0),
 '811': datetime.datetime(2018, 5, 6, 0, 0),
 '825': datetime.datetime(2018, 5, 9, 0, 0),
 '1055': datetime.datetime(2018, 5, 8, 0, 0),
 '1215': datetime.datetime(2018, 5, 11, 0, 0),
 '1030': datetime.datetime(2018, 5, 11, 0, 0),
 '955': datetime.datetime(2018, 5, 11, 0, 0),
 '142': datetime.datetime(2018, 1, 12, 0, 0),
 '1038': datetime.datetime(2018, 4, 4, 0, 0),
 '1170': datetime.datetime(2018, 4, 5, 0, 0),
 '1268': datetime.datetime(2018, 4, 6, 0, 0),
 '706': datetime.datetime(2018, 4, 7, 0, 0),
 '606': datetime.datetime(2018, 4, 8, 0, 0),
 '669': datetime.datetime(2018, 5, 12, 0, 0),
 '569': datetime.datetime(2018, 6, 2, 0, 0),
 '912': datetime.datetime(2018, 6, 6, 0, 0),
 '1062': datetime.datetime(2018, 5, 10, 0, 0),
 '956': datetime.datetime(2018, 6, 8, 0, 0),
 '777': datetime.datetime(2018, 6, 8, 0, 0),
 '402': datetime.datetime(2018, 1, 12, 0, 0),
 '15': datetime.datetime(2018, 3, 4, 0, 0),
 '134': datetime.datetime(2018, 2, 5, 0, 0),
 '1033': datetime.datetime(2018, 2, 6, 0, 0),
 '512': datetime.datetime(2017, 11, 10, 0, 0),
 '1243': datetime.datetime(2017, 11, 10, 0, 0),
 '1220': datetime.datetime(2017, 11, 10, 0, 0),
 '85': datetime.datetime(2017, 11, 11, 0, 0),
 '160': datetime.datetime(2017, 11, 11, 0, 0),
 '636': datetime.datetime(2018, 3, 5, 0, 0),
 '423': datetime.datetime(2018, 2, 9, 0, 0),
 '190': datetime.datetime(2018, 2, 11, 0, 0),
 '692': datetime.datetime(2018, 2, 11, 0, 0),
 '259': datetime.datetime(2018, 4, 7, 0, 0),
 '839': datetime.datetime(2017, 11, 13, 0, 0),
 '1161': datetime.datetime(2017, 11, 13, 0, 0),
 '1146': datetime.datetime(2017, 11, 16, 0, 0),
 '65': datetime.datetime(2017, 11, 16, 0, 0),
 '787': datetime.datetime(2017, 11, 16, 0, 0),
 '941': datetime.datetime(2018, 3, 10, 0, 0),
 '985': datetime.datetime(2018, 3, 11, 0, 0),
 '835': datetime.datetime(2017, 12, 3, 0, 0),
 '549': datetime.datetime(2017, 12, 3, 0, 0),
 '660': datetime.datetime(2017, 12, 3, 0, 0),
 '174': datetime.datetime(2017, 12, 3, 0, 0),
 '514': datetime.datetime(2017, 12, 4, 0, 0),
 '778': datetime.datetime(2017, 12, 7, 0, 0),
 '801': datetime.datetime(2017, 12, 8, 0, 0),
 '1077': datetime.datetime(2017, 12, 8, 0, 0),
 '808': datetime.datetime(2017, 12, 8, 0, 0),
 '528': datetime.datetime(2018, 4, 3, 0, 0),
 '1115': datetime.datetime(2018, 4, 8, 0, 0),
 '447': datetime.datetime(2018, 4, 24, 0, 0),
 '272': datetime.datetime(2018, 1, 8, 0, 0),
 '434': datetime.datetime(2018, 1, 12, 0, 0),
 '532': datetime.datetime(2018, 1, 12, 0, 0),
 '937': datetime.datetime(2018, 5, 6, 0, 0),
 '927': datetime.datetime(2018, 5, 13, 0, 0),
 '1022': datetime.datetime(2018, 5, 7, 0, 0),
 '410': datetime.datetime(2018, 5, 12, 0, 0),
 '1007': datetime.datetime(2018, 5, 12, 0, 0),
 '645': datetime.datetime(2018, 2, 9, 0, 0),
 '1217': datetime.datetime(2018, 6, 6, 0, 0),
 '762': datetime.datetime(2018, 6, 8, 0, 0),
 '897': datetime.datetime(2018, 6, 8, 0, 0),
 '1075': datetime.datetime(2018, 6, 9, 0, 0),
 '1188': datetime.datetime(2018, 2, 10, 0, 0),
 '1200': datetime.datetime(2018, 3, 4, 0, 0),
 '113': datetime.datetime(2018, 3, 4, 0, 0),
 '1082': datetime.datetime(2018, 3, 6, 0, 0),
 '828': datetime.datetime(2018, 3, 9, 0, 0),

In [143]:
len(accounts_in_good_standing)

445

In [144]:
def remove_free_trials(dataset):
    free_trails_list= []
    for row_dict in dataset:
        if row_dict['account_key'] in accounts_in_good_standing:
            free_trails_list.append(row_dict)
    return free_trails_list

In [145]:
quality_enrollments = remove_free_trials(true_enrollments)
quality_engagements = remove_free_trials(true_engagements)
quality_submissions = remove_free_trials(true_submissions)

In [146]:
print(len(quality_enrollments))
print(len(quality_engagements))
print(len(quality_submissions))

719
55675
1110

In [147]:
# How many students were active within the first week?

In [148]:
def engagements_within_first_week(date_join, date_of_first_engagement):
    time_delta = date_of_first_engagement - date_join
    if time_delta.days >= 0 and time_delta.days < 8:
        return True

for row_dict in quality_engagements:
    if row_dict['num_courses_visited'] > 0:
        row_dict['has_visited'] = 1
    else:
        row_dict['has_visited'] = 0

first_week_engagements = []
for row_dict in quality_engagements:
    if engagements_within_first_week(accounts_in_good_standing[row_dict['account_key']], row_dict['utc_date']):
        first_week_engagements.append(row_dict)

In [149]:
quality_engagements[0]

{'utc_date': datetime.datetime(2017, 11, 10, 0, 0),
 'num_courses_visited': 2,
 'total_minutes_visited': 136.1835995,
 'lessons_completed': 0,
 'projects_completed': 0,
 'account_key': '3',
 'has_visited': 1}

In [150]:
print(len(first_week_engagements))

3559

In [151]:
# How many minutes did each student spend online in the first week?

In [152]:
from collections import defaultdict

def compare(dataset, dict_key):
    new_data = defaultdict(list)
    for row_dict in dataset:
        account_key = row_dict[dict_key]
        new_data[account_key].append(row_dict)
    return new_data

In [153]:
engagements_grouped_by_account = compare(first_week_engagements, 'account_key')

In [154]:
# engagements_grouped_by_account['3'][0]['num_courses_visited']
engagements_grouped_by_account['3']

[{'utc_date': datetime.datetime(2017, 11, 10, 0, 0),
  'num_courses_visited': 2,
  'total_minutes_visited': 136.1835995,
  'lessons_completed': 0,
  'projects_completed': 0,
  'account_key': '3',
  'has_visited': 1},
 {'utc_date': datetime.datetime(2017, 11, 11, 0, 0),
  'num_courses_visited': 1,
  'total_minutes_visited': 11.0550435,
  'lessons_completed': 0,
  'projects_completed': 0,
  'account_key': '3',
  'has_visited': 1},
 {'utc_date': datetime.datetime(2017, 11, 12, 0, 0),
  'num_courses_visited': 1,
  'total_minutes_visited': 34.615231,
  'lessons_completed': 1,
  'projects_completed': 0,
  'account_key': '3',
  'has_visited': 1},
 {'utc_date': datetime.datetime(2017, 11, 13, 0, 0),
  'num_courses_visited': 1,
  'total_minutes_visited': 406.3332692,
  'lessons_completed': 3,
  'projects_completed': 0,
  'account_key': '3',
  'has_visited': 1},
 {'utc_date': datetime.datetime(2017, 11, 14, 0, 0),
  'num_courses_visited': 2,
  'total_minutes_visited': 91.475528,
  'lessons_completed': 0,
  'projects_completed': 0,
  'account_key': '3',
  'has_visited': 1},
 {'utc_date': datetime.datetime(2017, 11, 15, 0, 0),
  'num_courses_visited': 1,
  'total_minutes_visited': 148.2441033,
  'lessons_completed': 2,
  'projects_completed': 0,
  'account_key': '3',
  'has_visited': 1},
 {'utc_date': datetime.datetime(2017, 11, 16, 0, 0),
  'num_courses_visited': 0,
  'total_minutes_visited': 0.0,
  'lessons_completed': 0,
  'projects_completed': 0,
  'account_key': '3',
  'has_visited': 0},
 {'utc_date': datetime.datetime(2017, 11, 17, 0, 0),
  'num_courses_visited': 1,
  'total_minutes_visited': 195.6512002,
  'lessons_completed': 2,
  'projects_completed': 0,
  'account_key': '3',
  'has_visited': 1}]

In [155]:
# How many minutes did each student spend on the website total?
# IGNORE THIS QUESTION, BELOW IS TO SET-UP THE LAST (OR 2ND TO LAST) QUESTION

In [156]:
def sum_records(dataset, column):
    new_data = dict()
    for dict_key,dict_value in dataset.items():
        sum_ = 0
        for row in dict_value:
            sum_ += row[column]
        new_data[dict_key] = sum_
    return new_data

In [157]:
minutes_per_accounts = sum_records(engagements_grouped_by_account, 'total_minutes_visited')

In [158]:
minutes_per_accounts

{'3': 1023.5579746999999,
 '5': 370.82494396,
 '15': 1071.12533757,
 '18': 155.1361575,
 '19': 0.0,
 '24': 943.1881172000001,
 '25': 0.0,
 '31': 247.27557963999996,
 '34': 138.1789523,
 '42': 174.30704300000002,
 '43': 88.822038,
 '44': 731.72366783,
 '45': 979.7454166629999,
 '51': 0.0,
 '52': 3.227523833,
 '53': 43.53851617,
 '57': 750.894147533,
 '60': 0.0,
 '62': 293.3831222,
 '64': 589.58194586,
 '65': 422.27366,
 '67': 1123.02533437,
 '69': 0.0,
 '72': 883.9906950330001,
 '74': 90.48065633,
 '76': 17.658779,
 '78': 6.609209333,
 '79': 416.495983833,
 '85': 500.49217067,
 '88': 106.16380783,
 '90': 4.842514,
 '91': 70.37317134,
 '92': 715.4277596699999,
 '93': 932.7172561699999,
 '97': 494.84799353,
 '98': 531.4097201300001,
 '99': 425.60350947,
 '101': 188.92038351,
 '105': 573.58079867,
 '106': 535.168407333,
 '108': 164.270890837,
 '110': 1403.143966737,
 '111': 169.1595922,
 '113': 139.57379017,
 '119': 103.90436599,
 '123': 0.0,
 '130': 0.0,
 '132': 1428.3456270000001,
 '134': 1098.6832576400002,
 '136': 66.30446384,
 '138': 46.42543033,
 '140': 202.6228267,
 '141': 544.9926586,
 '142': 505.63867662999996,
 '143': 405.02286753,
 '147': 416.49688996,
 '148': 0.0,
 '150': 486.24643833700003,
 '151': 969.1894240600001,
 '153': 116.8988095,
 '157': 10.884649667,
 '159': 18.44071917,
 '160': 1011.9525945299999,
 '161': 531.8882432099999,
 '165': 1083.22753966,
 '168': 1198.3499316,
 '169': 223.6821162,
 '170': 586.70428494,
 '171': 2183.9339814,
 '174': 472.61704748999995,
 '178': 783.3383064,
 '179': 967.46286586,
 '180': 234.47278604000002,
 '181': 166.14326012700002,
 '185': 0.0,
 '187': 743.655930133,
 '190': 353.05917586000004,
 '191': 28.868115997,
 '193': 0.0,
 '197': 931.3076662,
 '203': 620.4744591699999,
 '208': 356.77551814000003,
 '217': 657.39103014,
 '220': 346.78228750000005,
 '221': 178.70479886999996,
 '227': 548.49517273,
 '229': 131.7264965,
 '243': 46.60514067,
 '251': 357.8209291,
 '253': 465.4912042,
 '256': 0.0,
 '258': 748.13000253,
 '259': 832.42184273,
 '261': 0.0,
 '263': 34.281020330000004,
 '264': 110.09569266,
 '265': 419.7968294,
 '268': 314.33318003,
 '270': 1123.238648,
 '272': 1207.3723326629997,
 '279': 375.05861866,
 '284': 283.2611105,
 '285': 183.175982167,
 '289': 1092.578964797,
 '293': 566.77326963,
 '306': 6.61027,
 '315': 952.1811420700001,
 '316': 1825.6310638700004,
 '321': 6.395196833,
 '322': 0.0,
 '323': 579.60225253,
 '329': 89.68924583,
 '334': 9.553760833,
 '335': 947.24981713,
 '338': 0.0,
 '339': 0.0,
 '343': 443.5831058,
 '347': 104.97653,
 '348': 445.67912980299997,
 '361': 1053.7764164300002,
 '362': 58.315108499999994,
 '366': 23.551663167,
 '367': 257.3663085,
 '378': 0.0,
 '386': 0.0,
 '388': 147.8970597,
 '394': 990.7801981700002,
 '397': 261.91549584,
 '402': 81.871438503,
 '404': 737.44397104,
 '407': 621.88870587,
 '408': 59.77253067,
 '410': 1007.8260931,
 '411': 0.0,
 '412': 108.9097063,
 '413': 578.95028613,
 '415': 183.21106814,
 '416': 934.515744067,
 '418': 86.78249267,
 '419': 26.205425502999997,
 '423': 0.0,
 '426': 0.0,
 '427': 413.54201817,
 '429': 0.0,
 '431': 77.97422683,
 '434': 832.77642093,
 '439': 278.86463337,
 '440': 86.82050367,
 '441': 1360.78769464,
 '442': 383.48329069700003,
 '444': 0.0,
 '447': 291.0635962,
 '458': 121.39381849699998,
 '460': 1427.54662863,
 '465': 260.92380287,
 '467': 210.01318516999999,
 '473': 0.0,
 '474': 285.75573753000003,
 '477': 793.77720249,
 '480': 0.0,
 '483': 869.7483835,
 '499': 440.401314,
 '500': 89.3707275,
 '504': 388.7726185,
 '505': 892.60699383,
 '507': 63.843047333,
 '512': 113.02499486699999,
 '514': 62.848290659999996,
 '520': 109.51497699999999,
 '521': 406.04536986,
 '523': 0.0,
 '524': 85.26222933,
 '525': 0.0,
 '528': 514.0743979700001,
 '529': 334.79837916699995,
 '532': 505.55668749999995,
 '534': 826.3571918700001,
 '541': 20.879544832999997,
 '544': 1421.7436063300001,
 '547': 0.0,
 '549': 124.2423835,
 '550': 18.95128533,
 '557': 0.0,
 '558': 1334.00295304,
 '563': 21.972605,
 '564': 766.53773037,
 '569': 1603.15193103,
 '571': 312.22133734,
 '576': 1366.5670150370001,
 '577': 120.55847800299998,
 '580': 851.429489267,
 '583': 843.5311485300001,
 '584': 0.0,
 '587': 181.354424837,
 '589': 168.39389986700002,
 '590': 71.15551016,
 '591': 0.0,
 '597': 1158.3549946,
 '599': 0.0,
 '601': 267.874047797,
 '602': 615.9597957,
 '606': 456.33328183,
 '610': 873.26167336,
 '611': 382.930370467,
 '612': 52.91365067,
 '618': 513.81269814,
 '622': 396.82058732999997,
 '623': 230.7043745,
 '624': 1197.02408723,
 '626': 95.12250383,
 '630': 537.7439134900001,
 '631': 237.76465218,
 '634': 324.29165179999995,
 '636': 185.39436433,
 '637': 89.05729567,
 '639': 416.14186616999996,
 '640': 0.0,
 '641': 340.7062775,
 '643': 218.9373798,
 '645': 1122.85546837,
 '649': 700.47435977,
 '650': 114.84451633,
 '651': 1460.3119036700002,
 '655': 333.60102137,
 '657': 0.0,
 '660': 225.80730217,
 '661': 92.55472316,
 '666': 254.5694942,
 '667': 144.12431733,
 '669': 22.73084533,
 '670': 454.2731635,
 '671': 162.016680833,
 '678': 100.0702155,
 '682': 25.243540000000003,
 '690': 159.93331549700002,
 '692': 16.604203,
 '693': 0.0,
 '696': 666.3290910299999,
 '697': 88.1119545,
 '698': 70.974336167,
 '702': 0.0,
 '704': 0.0,
 '705': 0.0,
 '706': 1467.2371881000001,
 '709': 88.0103965,
 '710': 3.561991333,
 '712': 253.23675753,
 '713': 139.060529,
 '718': 0.0,
 '719': 9.4907925,
 '720': 449.5952606370001,
 '722': 29.9067615,
 '726': 21.12844967,
 '729': 0.0,
 '730': 41.7199715,
 '732': 219.92606669999998,
 '735': 0.0,
 '736': 313.501810333,
 '743': 0.0,
 '744': 374.57610381,
 '746': 846.66856726,
 '752': 30.59517617,
 '753': 116.6288768,
 '756': 0.0,
 '757': 449.79538263000006,
 '759': 0.0,
 '761': 100.063683333,
 '762': 114.52385583,
 '769': 135.6825435,
 '776': 0.0,
 '777': 199.31994916,
 '778': 48.19741517,
 '779': 4.2604045,
 '780': 0.0,
 '785': 4.786497167,
 '786': 23.695871503,
 '787': 0.0,
 '792': 1589.158705,
 '793': 0.0,
 '796': 0.0,
 '800': 203.85678250299998,
 '801': 0.0,
 '804': 22.73466567,
 '808': 106.2993215,
 '811': 1138.31770153,
 '822': 27.94316733,
 '823': 0.0,
 '824': 260.470246496,
 '825': 49.29607483,
 '828': 392.68479187,
 '829': 129.762569,
 '831': 51.016355999999995,
 '833': 2.380932333,
 '835': 0.0,
 '836': 0.0,
 '839': 13.587055,
 '844': 839.243589237,
 '846': 32.68610117,
 '855': 92.68960016,
 '856': 0.0,
 '857': 0.0,
 '858': 260.948644837,
 '859': 2.541221667,
 '864': 53.1295885,
 '866': 0.0,
 '867': 0.0,
 '868': 13.442560666999999,
 '873': 30.2541315,
 '877': 26.52309817,
 '882': 0.0,
 '896': 0.0,
 '897': 22.08896567,
 '900': 0.0,
 '905': 108.98321334,
 '906': 0.0,
 '909': 63.3749175,
 '912': 0.0,
 '913': 72.9583085,
 '916': 65.7383995,
 '918': 21.086721,
 '919': 693.4264896600001,
 '923': 0.0,
 '927': 125.446569167,
 '932': 0.0,
 '934': 5.03956,
 '937': 222.16125416,
 '938': 69.45209899999999,
 '941': 2.999349667,
 '948': 94.32375533,
 '952': 194.51546903000002,
 '954': 91.64868467000001,
 '955': 240.59597452999998,
 '956': 6.806882833,
 '958': 0.0,
 '965': 796.0860388,
 '966': 26.584319333000003,
 '969': 24.966902329999996,
 '972': 96.11371283999999,
 '976': 65.05270717,
 '983': 0.0,
 '984': 188.307856327,
 '985': 46.494977,
 '988': 61.420162,
 '989': 0.0,
 '1007': 0.0,
 '1009': 0.0,
 '1011': 164.936009491,
 '1013': 4.3800225,
 '1015': 100.326129003,
 '1019': 75.87298200000001,
 '1022': 23.549948167,
 '1029': 3.508856667,
 '1030': 218.55650866300002,
 '1033': 959.95343761,
 '1038': 0.0,
 '1040': 12.98248983,
 '1042': 45.5670335,
 '1049': 37.853095,
 '1052': 117.1958063,
 '1053': 81.44155333,
 '1054': 0.0,
 '1055': 71.57364067,
 '1058': 0.0,
 '1060': 1768.5227493,
 '1062': 366.31941634000003,
 '1066': 0.0,
 '1071': 0.0,
 '1074': 0.0,
 '1075': 90.6038805,
 '1077': 152.2132672,
 '1082': 51.1061375,
 '1088': 0.0,
 '1089': 102.89907667,
 '1090': 0.0,
 '1094': 464.47214951,
 '1095': 30.09755267,
 '1099': 108.88937200999999,
 '1102': 0.0,
 '1103': 0.0,
 '1107': 73.62896584,
 '1111': 0.0,
 '1115': 0.0,
 '1117': 0.0,
 '1118': 89.38367816,
 '1121': 20.215805333,
 '1123': 12.65633967,
 '1124': 0.0,
 '1128': 55.827512667,
 '1130': 278.31484216,
 '1139': 321.751190867,
 '1140': 208.498611167,
 '1142': 0.0,
 '1146': 105.577247997,
 '1153': 679.80029763,
 '1160': 2.704084833,
 '1161': 87.81235717,
 '1163': 80.21072266,
 '1167': 1229.5553959630001,
 '1170': 91.43698283,
 '1174': 76.1418825,
 '1175': 2.7094835,
 '1178': 0.0,
 '1183': 258.8492892,
 '1188': 411.07007933,
 '1189': 481.1140735,
 '1194': 168.1376205,
 '1198': 6.5907805,
 '1199': 4.714764167,
 '1200': 824.427983767,
 '1201': 526.6600761,
 '1202': 48.679263336999995,
 '1204': 381.32434615999995,
 '1205': 0.0,
 '1207': 26.4703245,
 '1208': 114.066953,
 '1210': 430.78566787,
 '1211': 3.564415833,
 '1212': 0.0,
 '1214': 12.822523,
 '1215': 1360.7287002000003,
 '1217': 32.0539045,
 '1220': 118.30495933,
 '1226': 0.0,
 '1236': 6.864152333,
 '1242': 49.1640855,
 '1243': 62.91143633,
 '1244': 53.59622567,
 '1247': 84.73468383299999,
 '1248': 3.509181833,
 '1249': 31.995718997,
 '1253': 0.0,
 '1254': 187.32349033,
 '1259': 97.98160567,
 '1260': 0.0,
 '1264': 2.017341333,
 '1266': 0.0,
 '1268': 11.33088867,
 '1277': 0.0,
 '1285': 32.42569817,
 '1287': 0.0,
 '1289': 5.456283333,
 '1292': 233.20550336600002,
 '1299': 117.9899268,
 '1303': 0.0,
 '1305': 9.771473833}

In [159]:
# HOMEWORK:

# Take a look at data and come up with 3 good questions and use some of the methods done in this 
# Jupyter Notebook to successfully answer the questions.

In [160]:
#1  What is the average minutes per account?

In [161]:
def avg_time(account_info):
    average = 0
    for key in account_info:
        average += account_info[key]
    average = average / len(account_info)
    return average

average_time_per_account = avg_time(minutes_per_accounts)

print(f"The # of minutes spent online per account is {round(average_time_per_account) } minutes. ")

The # of minutes spent online per account is 280 minutes.

In [162]:
#2 Number of courses visited vs number completed on average?

In [163]:
def courses_completed(engagement_info):
    value = 0
    for key in engagement_info:
        for length in range(len(engagement_info[key]) - 1):
            value += engagement_info[key][length]['lessons_completed']
    return value

def courses_visited(engagement_info):
    value = 0
    for key in engagement_info:
        for length in range(len(engagement_info[key]) - 1):
            value += engagement_info[key][length]['num_courses_visited']
    return value

average_complete_per_visit = courses_completed(engagements_grouped_by_account) / courses_visited(engagements_grouped_by_account)
average_visit_per_complete =  courses_visited(engagements_grouped_by_account) / courses_completed(engagements_grouped_by_account)

print(f"The Average Completion Rate Per Visit is {round(average_complete_per_visit * 100,2)}%, whereas the Average Visit Needed Per Completion is {round(average_visit_per_complete, 5)}. Exciting isn't it? ")

The Average Completion Rate Per Visit is 29.97%, whereas the Average Visit Needed Per Completion is 3.33619. Exciting isn't it?

In [164]:
#3 Logins needed to finish a course per user

In [165]:
def courses_completed_per_user(engagement_info):
    value = dict()
    for key in engagement_info:
        sum = 0
        for length in range(len(engagement_info[key]) - 1):
            sum += engagement_info[key][length]['lessons_completed']
        value[key] = sum
    return value


def logins_per_user(engagement_info):
    value = dict()
    for key in engagement_info:
        value[key] = len(engagement_info[key])
    return value

def logins_per_course(courses, logins):
    logins_dict = dict()
    for key in logins:
        if logins[key] == 0 or courses[key] == 0:
            logins_dict[key] = 0
        else:
            logins_dict[key] = logins[key]/courses[key]
    return logins_dict


logins_per_course_complete = logins_per_course(courses_completed_per_user(engagements_grouped_by_account), logins_per_user(engagements_grouped_by_account))

for key in logins_per_course_complete:
    if logins_per_course_complete[key] == 0:
        print(f"User with Account #{key} was unable to finish any course, with an average login per course of {logins_per_course_complete[key]}. Maybe offer a discount to get them back online! ")
    elif logins_per_course_complete[key] <= 5:
        print(f"For User with Account #{key} it takes on average {round(logins_per_course_complete[key], 2)} attempts to complete a single course. This one is an overachiever! Offer them some more discounts :) ")
    elif logins_per_course_complete[key] > 5:
        print(f"For User with Account #{key} it takes on average {round(logins_per_course_complete[key], 2)} attempts to complete a single course. This user takes a bit longer, maybe offer an extension on their membership! :D  ")

For User with Account #3 it takes on average 1.33 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
User with Account #5 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
For User with Account #15 it takes on average 8.0 attempts to complete a single course. This user takes a bit longer, maybe offer an extension on their membership! :D
User with Account #18 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
User with Account #19 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
For User with Account #24 it takes on average 2.0 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
User with Account #25 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
User with Account #31 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
For User with Account #34 it takes on average 8.0 attempts to complete a single course. This user takes a bit longer, maybe offer an extension on their membership! :D
User with Account #42 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
User with Account #43 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
For User with Account #44 it takes on average 4.0 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
For User with Account #45 it takes on average 2.67 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
User with Account #51 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
User with Account #52 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
User with Account #53 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
For User with Account #57 it takes on average 2.67 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
User with Account #60 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
For User with Account #62 it takes on average 8.0 attempts to complete a single course. This user takes a bit longer, maybe offer an extension on their membership! :D
For User with Account #64 it takes on average 1.33 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
For User with Account #65 it takes on average 2.67 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
For User with Account #67 it takes on average 4.0 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
User with Account #69 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
For User with Account #72 it takes on average 1.14 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
User with Account #74 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
User with Account #76 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
User with Account #78 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
For User with Account #79 it takes on average 8.0 attempts to complete a single course. This user takes a bit longer, maybe offer an extension on their membership! :D
For User with Account #85 it takes on average 8.0 attempts to complete a single course. This user takes a bit longer, maybe offer an extension on their membership! :D
User with Account #88 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
User with Account #90 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
User with Account #91 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
For User with Account #92 it takes on average 2.67 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
For User with Account #93 it takes on average 2.67 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
For User with Account #97 it takes on average 4.0 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
For User with Account #98 it takes on average 4.0 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
For User with Account #99 it takes on average 4.0 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
User with Account #101 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
User with Account #105 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
User with Account #106 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
User with Account #108 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
For User with Account #110 it takes on average 0.89 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
For User with Account #111 it takes on average 8.0 attempts to complete a single course. This user takes a bit longer, maybe offer an extension on their membership! :D
User with Account #113 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
User with Account #119 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
User with Account #123 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
User with Account #130 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
For User with Account #132 it takes on average 8.0 attempts to complete a single course. This user takes a bit longer, maybe offer an extension on their membership! :D
For User with Account #134 it takes on average 1.33 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
User with Account #136 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
User with Account #138 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
User with Account #140 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
For User with Account #141 it takes on average 4.0 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
User with Account #142 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
For User with Account #143 it takes on average 8.0 attempts to complete a single course. This user takes a bit longer, maybe offer an extension on their membership! :D
For User with Account #147 it takes on average 1.33 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
User with Account #148 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
For User with Account #150 it takes on average 8.0 attempts to complete a single course. This user takes a bit longer, maybe offer an extension on their membership! :D
For User with Account #151 it takes on average 1.14 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
For User with Account #153 it takes on average 8.0 attempts to complete a single course. This user takes a bit longer, maybe offer an extension on their membership! :D
User with Account #157 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
For User with Account #159 it takes on average 8.0 attempts to complete a single course. This user takes a bit longer, maybe offer an extension on their membership! :D
For User with Account #160 it takes on average 4.0 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
For User with Account #161 it takes on average 2.67 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
For User with Account #165 it takes on average 4.0 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
For User with Account #168 it takes on average 1.33 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
User with Account #169 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
For User with Account #170 it takes on average 4.0 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
For User with Account #171 it takes on average 1.6 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
For User with Account #174 it takes on average 8.0 attempts to complete a single course. This user takes a bit longer, maybe offer an extension on their membership! :D
For User with Account #178 it takes on average 1.33 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
For User with Account #179 it takes on average 1.6 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
User with Account #180 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
User with Account #181 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
User with Account #185 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
For User with Account #187 it takes on average 4.0 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
For User with Account #190 it takes on average 8.0 attempts to complete a single course. This user takes a bit longer, maybe offer an extension on their membership! :D
User with Account #191 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
User with Account #193 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
For User with Account #197 it takes on average 0.89 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
For User with Account #203 it takes on average 4.0 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
For User with Account #208 it takes on average 8.0 attempts to complete a single course. This user takes a bit longer, maybe offer an extension on their membership! :D
For User with Account #217 it takes on average 4.0 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
For User with Account #220 it takes on average 4.0 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
For User with Account #221 it takes on average 8.0 attempts to complete a single course. This user takes a bit longer, maybe offer an extension on their membership! :D
For User with Account #227 it takes on average 2.67 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
User with Account #229 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
User with Account #243 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
For User with Account #251 it takes on average 8.0 attempts to complete a single course. This user takes a bit longer, maybe offer an extension on their membership! :D
User with Account #253 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
User with Account #256 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
For User with Account #258 it takes on average 2.67 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
For User with Account #259 it takes on average 2.67 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
User with Account #261 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
User with Account #263 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
For User with Account #264 it takes on average 8.0 attempts to complete a single course. This user takes a bit longer, maybe offer an extension on their membership! :D
For User with Account #265 it takes on average 2.67 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
For User with Account #268 it takes on average 1.6 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
For User with Account #270 it takes on average 0.89 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
For User with Account #272 it takes on average 1.0 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
For User with Account #279 it takes on average 8.0 attempts to complete a single course. This user takes a bit longer, maybe offer an extension on their membership! :D
For User with Account #284 it takes on average 4.0 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
User with Account #285 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
For User with Account #289 it takes on average 1.14 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
For User with Account #293 it takes on average 2.0 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
User with Account #306 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
For User with Account #315 it takes on average 2.67 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
For User with Account #316 it takes on average 0.89 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
User with Account #321 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
User with Account #322 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
For User with Account #323 it takes on average 4.0 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
User with Account #329 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
User with Account #334 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
For User with Account #335 it takes on average 4.0 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
User with Account #338 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
User with Account #339 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
User with Account #343 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
User with Account #347 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
For User with Account #348 it takes on average 2.67 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
For User with Account #361 it takes on average 0.8 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
User with Account #362 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
User with Account #366 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
For User with Account #367 it takes on average 8.0 attempts to complete a single course. This user takes a bit longer, maybe offer an extension on their membership! :D
User with Account #378 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
User with Account #386 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
For User with Account #388 it takes on average 8.0 attempts to complete a single course. This user takes a bit longer, maybe offer an extension on their membership! :D
For User with Account #394 it takes on average 4.0 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
For User with Account #397 it takes on average 8.0 attempts to complete a single course. This user takes a bit longer, maybe offer an extension on their membership! :D
User with Account #402 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
For User with Account #404 it takes on average 4.0 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
For User with Account #407 it takes on average 2.0 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)
User with Account #408 was unable to finish any course, with an average login per course of 0. Maybe offer a discount to get them back online!
For User with Account #410 it takes on average 4.0 attempts to complete a single course. This one is an overachiever! Offer them some more discounts :)

### HOMEWORK PROBLEMS

In [166]:
#1 How many students were active on the website within the first week?

In [172]:
from datetime import date
import numpy as np
import pandas as pd

In [176]:
engagement = pd.read_csv('engagements.csv')
enrollment = pd.read_csv('enrollments.csv')
submissions = pd.read_csv('submissions.csv')

In [177]:
df_engagement = pd.DataFrame(data=engagement, index=None)
df_enrollment = pd.DataFrame(data=enrollment, index=None)
df_submissions = pd.DataFrame(data=submissions, index=None)

In [179]:
df_enrollment.rename(columns={"account_key": 'acct'}, inplace=True)
ee_merge = pd.merge(df_engagement, df_enrollment[['join_date', 'acct']], on='acct', how='right')
ee_merge

,acct,utc_date,num_courses_visited,total_minutes_visited,lessons_completed,projects_completed,join_date
0,700,2017-11-10,1.0,15.185969,0.0,0.0,2017-11-10
1,700,2017-11-11,0.0,0.000000,0.0,0.0,2017-11-10
2,700,2017-11-12,0.0,0.000000,0.0,0.0,2017-11-10
3,700,2017-11-13,0.0,0.000000,0.0,0.0,2017-11-10
4,700,2017-11-14,1.0,107.142940,0.0,0.0,2017-11-10
...,...,...,...,...,...,...,...
196268,818,2018-01-09,0.0,0.000000,0.0,0.0,2018-01-07
196269,818,2018-01-10,0.0,0.000000,0.0,0.0,2018-01-07
196270,818,2018-01-11,0.0,0.000000,0.0,0.0,2018-01-07
196271,1069,NaN,NaN,NaN,NaN,NaN,2018-06-01
196272,1101,NaN,NaN,NaN,NaN,NaN,2018-02-25

In [180]:
ee_merge.utc_date = pd.to_datetime(ee_merge['utc_date'])
ee_merge.join_date = pd.to_datetime(ee_merge['join_date'])
time_delta_of_seven = ee_merge.loc[(ee_merge['utc_date'] - ee_merge['join_date']).dt.days <= 7]

In [181]:
filtered = time_delta_of_seven.drop_duplicates(subset='acct')
filtered

,acct,utc_date,num_courses_visited,total_minutes_visited,lessons_completed,projects_completed,join_date
0,700,2017-11-10,1.0,15.185969,0.0,0.0,2017-11-10
6,429,2017-11-10,3.0,25.481334,0.0,0.0,2017-11-10
444,60,2017-11-10,2.0,7.778121,0.0,0.0,2017-11-10
1314,1300,2017-11-10,1.0,2.625080,0.0,0.0,2017-11-10
1320,369,2017-11-10,0.0,0.000000,0.0,0.0,2017-11-10
...,...,...,...,...,...,...,...
192467,874,2018-08-23,0.0,0.000000,0.0,0.0,2018-08-22
192472,686,2018-08-23,1.0,9.612110,0.0,0.0,2018-08-23
192473,448,2017-11-05,0.0,0.000000,0.0,0.0,2017-11-10
195130,312,2017-11-10,1.0,4.326470,0.0,0.0,2017-11-10
196266,818,2018-01-07,1.0,38.961961,0.0,0.0,2018-01-07

In [ ]:
#2 How many minutes did each student spend on the website total?

In [182]:
visited = pd.merge(df_engagement, df_enrollment[['join_date', 'acct']], on='acct', how='right')
visited = visited.drop_duplicates(subset='acct')
visited['total_minutes_visited']

0         15.185969
6         25.481334
444        7.778121
1314       2.625080
1320       0.000000
            ...
195128          NaN
195130     4.326470
196266    38.961961
196271          NaN
196272          NaN
Name: total_minutes_visited, Length: 1302, dtype: float64

In [184]:
visited_clean = visited[visited['total_minutes_visited'].notna()]
visited_clean

,acct,utc_date,num_courses_visited,total_minutes_visited,lessons_completed,projects_completed,join_date
0,700,2017-11-10,1.0,15.185969,0.0,0.0,2017-11-10
6,429,2017-11-10,3.0,25.481334,0.0,0.0,2017-11-10
444,60,2017-11-10,2.0,7.778121,0.0,0.0,2017-11-10
1314,1300,2017-11-10,1.0,2.625080,0.0,0.0,2017-11-10
1320,369,2017-11-10,0.0,0.000000,0.0,0.0,2017-11-10
...,...,...,...,...,...,...,...
192467,874,2018-08-23,0.0,0.000000,0.0,0.0,2018-08-22
192472,686,2018-08-23,1.0,9.612110,0.0,0.0,2018-08-23
192473,448,2017-11-05,0.0,0.000000,0.0,0.0,2017-11-10
195130,312,2017-11-10,1.0,4.326470,0.0,0.0,2017-11-10
196266,818,2018-01-07,1.0,38.961961,0.0,0.0,2018-01-07